import {
  VESICASH_APP_BASE_URL,
  VESICASH_API_BASE_URL,
  VESICASH_API_VERSION,
  VESICASH_PRIVATE_KEY,
  VESICASH_PUBLIC_KEY,
} from "@/env";

export const VESICASH_AUTH_USER = "VESICASH_AUTH_USER";
export const VESICASH_AUTH_TOKEN = "VESICASH_AUTH_TOKEN";

// ENVIRONMENT CONSTANTS
export const VESICASH_APP_URL = VESICASH_APP_BASE_URL;
export const VESICASH_API_URL = `${VESICASH_API_BASE_URL}/${VESICASH_API_VERSION}`;
export const VESICASH_PRIVATE_KEY_TOKEN = VESICASH_PRIVATE_KEY;
export const VESICASH_PUBLIC_KEY_TOKEN = VESICASH_PUBLIC_KEY;
